// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjeougsaxfuznmquezon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZW91Z3NheGZ1em5tcXVlem9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjAxOTAyOTcsImV4cCI6MjAzNTc2NjI5N30.vZ2mKg4WIZSUUPt36qu9vOr4Lfm_rLkBwqMNbWvINVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);